{
 "title": "Aruba Interface",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device_name", "label": "Device", "query": { "query": "aruba_up" } },
   {
    "name": "int_name",
    "label": "Interface",
    "query": {
     "query": "aruba_interface_up{target=~\"$device_name\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aruba_interface_up{target=~\"$device_name\",name=~\"$int_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Traffic in Bytes ($int_name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "repeat": "int_desc",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(aruba_interface_tx_bytes{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Tx"
    },
    {
     "expr": "rate(aruba_interface_rx_bytes{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Rx"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(aruba_interface_tx_errors{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])+rate(aruba_interface_rx_errors{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Traffic in Packets ($int_name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(aruba_interface_tx_packets{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Tx"
    },
    {
     "expr": "rate(aruba_interface_rx_packets{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Rx"
    }
   ]
  },
  {
   "title": "Interface Drops",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "rate(aruba_interface_tx_drops{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])+rate(aruba_interface_rx_drops{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Packets by Type ($int_name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(aruba_interface_tx_unicast{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Tx Ucast"
    },
    {
     "expr": "rate(aruba_interface_rx_unicast{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Rx Ucast"
    },
    {
     "expr": "rate(aruba_interface_tx_broadcast{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Tx Bcast"
    },
    {
     "expr": "rate(aruba_interface_rx_broadcast{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Rx Bcast"
    },
    {
     "expr": "rate(aruba_interface_tx_multicast{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Tx Mcast"
    },
    {
     "expr": "rate(aruba_interface_rx_multicast{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Rx Mcast"
    }
   ]
  },
  {
   "title": "Errors and Drops ($int_name)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(aruba_interface_tx_errors{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Tx Errors"
    },
    {
     "expr": "rate(aruba_interface_rx_errors{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Rx Errors"
    },
    {
     "expr": "rate(aruba_interface_tx_drops{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Tx Drops"
    },
    {
     "expr": "rate(aruba_interface_rx_drops{target=~\"$device_name\",name=~\"$int_name\"}[$__rate_interval])",
     "legendFormat": "{{name}} - Rx Drops"
    }
   ]
  }
 ]
}