{
 "title": "Aruba Device",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device_name", "label": "Device", "query": { "query": "aruba_up" } }
  ]
 },
 "panels": [
  {
   "title": "Device Type and Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "aruba_system_version{target=~\"$device_name\"}"
    },
    {
     "expr": "aruba_up{target=~\"$device_name\"}"
    }
   ]
  },
  {
   "title": "% CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aruba_system_cpu_used_percent{target=~\"$device_name\"}",
     "legendFormat": "{{type}} "
    }
   ]
  },
  {
   "title": "% Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(aruba_system_memory_used{target=~\"$device_name\"}/aruba_system_memory_total{target=~\"$device_name\"})*100",
     "legendFormat": "{{type}} "
    }
   ]
  },
  {
   "title": "Overall Traffic Over Time (in Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "repeat": "int_desc",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(aruba_interface_tx_bytes{target=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(rate(aruba_interface_rx_bytes{target=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Overall Traffic Over Time (in Packets)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(aruba_interface_tx_packets{target=~\"$device_name\"}[$__rate_interval]))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(rate(aruba_interface_rx_packets{target=~\"$device_name\"}[$__interval]))",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aruba_interface_up{target=~\"$device_name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}