{
 "title": "Aruba Summary",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "device_name", "label": "Device", "query": { "query": "aruba_up" } }
  ]
 },
 "panels": [
  {
   "title": "Device Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(aruba_up == 1)", "legendFormat": "Up" },
    { "expr": "sum(aruba_up == 0)", "legendFormat": "Down" }
   ]
  },
  {
   "title": "Device Status Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(aruba_up{target=~\"$device_name\"}[$__rate_interval])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Current Device Status",
   "type": "stat",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aruba_up{target=~\"$device_name\"}",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}